name: CI
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

permissions:
  contents: read

jobs:
  main:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: 'stable'

      - name: Unit tests
        run: go test -covermode=atomic -race -v ./pkg/...

      - name: Integration tests
        run: go test -v ./cmd/vens/... -run TestScript

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          args: --timeout=10m --verbose

      - run: go install ./cmd/vens
